<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-ios;net10.0-android;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<PackageId>NeuroSpeech.Positron</PackageId>
		<AssemblyName>NeuroSpeech.Positron</AssemblyName>
		<RootNamespace>NeuroSpeech.Positron</RootNamespace>
		<Version>1.0.1</Version>
		<Nullable>enable</Nullable>
		<SingleProject>true</SingleProject>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">16.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">17.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<EmbedAllSources>True</EmbedAllSources>
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
		<Compile Include="..\yantra\YantraJS.Core\**\*.cs">
			<Link>Platforms\Android\Engine\%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Resources\Positron.js" />
	  <None Remove="Resources\TSLib.js" />
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Include="Resources\Positron.js" />
	  <EmbeddedResource Include="Resources\TSLib.js" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="15.0.0" />
		<PackageReference Include="MimeKit" Version="4.17.0" />
		<PackageReference Include="Nerdbank.GitVersioning" Version="3.10.91">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.90" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.11.0.1" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" Version="2.11.0.1" />
		<PackageReference Include="YantraJS.ExpressionCompiler" Version="1.2.419" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.90" />
		<PackageReference Include="Xamarin.Firebase.Messaging" Version="125.1.1" />
		<PackageReference Include="Xamarin.AndroidX.Media3.Common" Version="1.10.1.1" />
		<PackageReference Include="Xamarin.AndroidX.Media3.Transformer" Version="1.10.1.1" />
		<ProjectReference Include="..\yantra\YantraJS.ExpressionCompiler\YantraJS.ExpressionCompiler.csproj" />
		<ProjectReference Include="YantraJS.JSClassGenerator" Version="1.2.462" OutputItemType="Analyzer" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Platforms\iOS\MauiAppBuilderExtensions.iOS.cs">
	    <ExcludeFromCurrentConfiguration>true</ExcludeFromCurrentConfiguration>
	  </Compile>
	</ItemGroup>

</Project>