name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install .NET MAUI
      shell: bash
      run: |
        dotnet nuget locals all --clear 
        dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
        dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json


    - name: Build
      run: dotnet build ./Positron/Positron.csproj
    # - name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack ./Positron/Positron.csproj --no-restore

    - name: Publish Eternity
      run: dotnet nuget push **/*.nupkg -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json --no-symbols
      env:
         NUGET_TOKEN: ${{secrets.PUBLIC_NUGET_TOKEN}}

    - name: Publish Eternity Proget
      run: dotnet nuget push **/*.nupkg -k ${NUGET_KEY} -s ${NUGET_SOURCE} --no-symbols
      env:
         NUGET_SOURCE: ${{secrets.PROGET_NUGET}}
         NUGET_KEY: ${{secrets.PROGET_NUGET_TOKEN}}  

    - name: Create tag
      uses: actions/github-script@v6
      with:
        script: |
          const { NBGV_SemVer2 } = process.env
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/v${NBGV_SemVer2}`,
            sha: context.sha
          })    